#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Quick Voice — one-command server deployment.
#
# Deploys the signaling server (WebRTC + APK updates), coturn (TURN for
# cross-network calls) and Caddy (automatic HTTPS) via Docker.
#
# Prerequisites:
#   • A running Ubuntu 22.04+ VPS with a public IP.
#   • Ports 80, 443, 3478/tcp+udp, 5349/tcp, 49152-65535/udp open in both
#     the cloud security list (VCN) AND the local ufw.
#   • Docker installed (the script does this if missing).
#
# Usage:
#   scp -r deploy server <user>@<ip>:/opt/quickvoice/
#   ssh <user>@<ip>
#   cd /opt/quickvoice/deploy
#   sudo bash setup.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; BOLD='\033[1m'; NC='\033[0m'
info() { printf "${GREEN}▸${NC} %s\n" "$*"; }
fail() { printf "${RED}✖ %s${NC}\n" "$*" >&2; exit 1; }

DEPLOY_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$DEPLOY_DIR/.." && pwd)"

# ── 1. Get required values (env vars or interactive prompts) ───────────────
# Supports non-interactive use via environment variables:
#   QV_SUBDOMAIN, QV_DUCKDNS_TOKEN, QV_TURN_PASSWORD
echo ""
echo "${BOLD}Quick Voice Server Setup${NC}"
echo "========================"
echo ""

if [ -z "${QV_SUBDOMAIN:-}" ]; then
    read -rp "DuckDNS subdomain (without .duckdns.org): " SUBDOMAIN
else
    SUBDOMAIN="$QV_SUBDOMAIN"
fi
SUBDOMAIN="${SUBDOMAIN%%.duckdns.org}"
[ -z "$SUBDOMAIN" ] && fail "Subdomain cannot be empty."

if [ -z "${QV_DUCKDNS_TOKEN:-}" ]; then
    read -rp "DuckDNS token: " DUCKDNS_TOKEN
else
    DUCKDNS_TOKEN="$QV_DUCKDNS_TOKEN"
fi
[ -z "$DUCKDNS_TOKEN" ] && fail "Token cannot be empty."

if [ -z "${QV_TURN_PASSWORD:-}" ]; then
    read -rsp "TURN password (for cross-network calls): " TURN_PASSWORD
    echo ""
else
    TURN_PASSWORD="$QV_TURN_PASSWORD"
fi
[ -z "$TURN_PASSWORD" ] && fail "TURN password cannot be empty."

DOMAIN="${SUBDOMAIN}.duckdns.org"

echo ""
info "Domain:       ${DOMAIN}"
info "TURN user:    quickvoice / $(printf '%0.s*' $(seq 1 ${#TURN_PASSWORD}))"
echo ""

# ── 2. Install Docker if missing ───────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
    info "Docker installed."
else
    info "Docker is already installed."
fi

# ── 3. Open ufw (ignore errors if inactive or not installed) ───────────────
if command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -q "Status: active"; then
    info "Opening ufw ports..."
    for p in 80/tcp 443/tcp 3478/tcp 3478/udp 5349/tcp; do ufw allow "$p" >/dev/null 2>&1 || true; done
    ufw allow 49152:65535/udp >/dev/null 2>&1 || true
    info "ufw ports opened."
fi

# ── 4. Write Caddyfile ─────────────────────────────────────────────────────
info "Writing Caddyfile..."
cat > "$DEPLOY_DIR/Caddyfile" <<CADDY
# Managed by setup.sh — edit by hand or re-run setup.sh.
${DOMAIN} {
    reverse_proxy signaling:8080
    encode zstd gzip
    header X-Content-Type-Options nosniff
    header X-Frame-Options DENY
}
CADDY
info "Caddyfile written."

# ── 5. Write coturn.conf ───────────────────────────────────────────────────
info "Writing coturn.conf..."
cat > "$DEPLOY_DIR/coturn.conf" <<COTURN
# Managed by setup.sh — change user password here or re-run setup.sh.
listening-port=3478
tls-listening-port=5349
realm=quickvoice
fingerprint
lt-cred-mech
user=quickvoice:${TURN_PASSWORD}
min-port=49152
max-port=65535
log-file=stdout
COTURN
info "coturn.conf written."

# ── 6. DuckDNS auto-update ─────────────────────────────────────────────────
info "Setting up DuckDNS IP auto-update (every 5 min)..."
cat > /usr/local/bin/quickvoice-duckdns <<DUCKDNS
#!/usr/bin/env bash
# Auto-generated by setup.sh. Updates DuckDNS IP for ${DOMAIN}.
curl -fsS "https://www.duckdns.org/update?domains=${SUBDOMAIN}&token=${DUCKDNS_TOKEN}&ip=" >/dev/null 2>&1
DUCKDNS
chmod +x /usr/local/bin/quickvoice-duckdns
/usr/local/bin/quickvoice-duckdns || info "DuckDNS initial update skipped (VPS may not have public IP yet)."
(crontab -l 2>/dev/null | grep -v quickvoice-duckdns; echo "*/5 * * * * /usr/local/bin/quickvoice-duckdns") | crontab -
info "DuckDNS cron installed."

# ── 7. Ensure releases dir exists ──────────────────────────────────────────
mkdir -p "$REPO_DIR/server/releases"

# ── 8. Build & start ───────────────────────────────────────────────────────
info "Building and starting Docker stack..."
cd "$DEPLOY_DIR"
docker compose up -d --build 2>&1 | tail -20

# ── 9. Wait for startup ────────────────────────────────────────────────────
info "Waiting for services to start..."
sleep 8

# ── 10. Verify ─────────────────────────────────────────────────────────────
VERIFY="$(curl -fsS http://localhost:8080/api/version 2>/dev/null || true)"
if echo "$VERIFY" | grep -q "versionName"; then
    info "Signaling server is running: $VERIFY"
else
    echo ""
    echo "⚠  Server may still be starting. Check with:"
    echo "   cd $DEPLOY_DIR && docker compose logs -f"
    echo ""
    exit 0
fi

# ── Done ───────────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "${BOLD} Quick Voice Server — Deployment Complete${NC}"
echo "============================================================"
echo ""
echo "  Signaling URL (HTTPS):  https://${DOMAIN}/signaling"
echo "  Signaling URL (WSS):    wss://${DOMAIN}/signaling"
echo ""
echo "  TURN (for cross-network calls):"
echo "    URL:      turn://${DOMAIN}:3478"
echo "    Username: quickvoice"
echo "    Password: ${TURN_PASSWORD}"
echo ""
echo "  APK Update endpoint:"
echo "    https://${DOMAIN}/api/version"
echo "    https://${DOMAIN}/apk/QuickVoiceDialer.apk"
echo ""
echo "  Verify externally:    curl -k https://${DOMAIN}/api/version"
echo "  Publish new APK:      cp app.apk ${REPO_DIR}/server/releases/"
echo "  Update version info:  edit ${REPO_DIR}/server/releases/version.json"
echo ""
echo "  Configure each phone:"
echo "    Settings → Wi-Fi calls"
echo "    Signaling: wss://${DOMAIN}/signaling"
echo "    TURN:      turn://${DOMAIN}:3478  /  quickvoice  /  ${TURN_PASSWORD}"
echo ""
echo "============================================================"
echo ""
